### ISSUE TITLE
Advanced Topics

### ISSUE THREAD

**Issue by nzoschke** [convox/guide#4]
This guide covers the basics. It should also offer links to some advanced topics. Some ideas...
- Picking A Base Image
- Vendoring Private Dependencies
- Optimizing Image Build Times
- Multiple Dockerfiles
- Balancer Header Injection
- Balancer SSL Certificates
- End-to-End Encryption
- Development Database Persistence
- Data Migrations
- [Twelve-Factor Backing Services](https://12factor.net/backing-services)
- Graceful Handling of Linked Service Unavailability
- Avoiding Service Discovery
- Container File Syncing

**Comment by soulshake** [comment]
This issue was moved to convox/site#335
