### ISSUE TITLE
Resource -> Database

### ISSUE THREAD

**Issue by nzoschke** [convox/guide#7]
Talking about abstract "development resources" seems to be confusing. Instead we can discuss more directly the technique for running a "Database" like Redis in development.
- Cut the "Resource" section
- Rewrite "Link" as explicit connections between "Services"
- Add a "Database" section after "Links"
- Discuss "Databases" in development as Containers very explicitly. Big benefit of one-command `convox start` for the entire app.

**Comment by soulshake** [comment]
This issue was moved to convox/site#334
