### ISSUE TITLE
This repo should be deleted

### ISSUE THREAD

**Issue by soulshake** [convox/guide#9]
The guide has been integrated into the [convox/site](https://github.com/convox/site) repo, so this is a duplicate and should go away.

I don't have access to do so-- @nzoschke can you do it?

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deal with deprecated Guide repo](https://trello.com/c/0WjE9hQO/1107-deal-with-deprecated-guide-repo)

**Comment by nzoschke** [comment]
Great call. Deleting!
